# Generated by Django 4.1.7 on 2024-02-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
