# Generated by Django 4.1.7 on 2024-02-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='productimage',
        ),
    ]
